server:
  port: 8763
spring:
  application:
    name: input-demo
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  cloud:
    stream:
        kafka:
          binder:
            brokers: localhost:9092
            zk-nodes: localhost:2182
            auto-add-partitions: true
            auto-create-topics: true
            min-partition-count: 1
          bindings:
           output:
              destination: event-demo
              content-type: text/plain
           producer:
              partitionCount: 1
        instance-count: 1
        instance-index: 0
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/